### ISSUE TITLE
Exception caught while trying to retrieve and decode certificate for https://172.17.8.47:8889

### ISSUE THREAD

**Issue by abrother94** [DMTF/Redfish-Protocol-Validator#15]
If we use following command to test

**python3 rf_protocol_validator.py -r https://172.17.8.47:8889 -u admin -p YourPaSsWoRd --no-cert-check --avoid-http-redirect**

will cause

**Exception caught while trying to retrieve and decode certificate for https://172.17.8.47:8889; exception: [Errno -2] Name or service not known**

and def test_certs_conform_to_x509v3   in assertions/security_details.py
...
conn.connect((rhost.netloc, port))
...

value of rhost.netloc is 172.17.4.47:8889 , but it should be 172.17.8.47 or the connection will fail

**Comment by billdodd** [comment]
@abrother94 Thanks for reporting this issue. I created PR #16 which I believe fixes the problem. But I do not have access to a live Redfish service to test. Could you test the fix in PR #16 to confirm if it solves your issue?

**Comment by abrother94** [comment]
> @abrother94 Thanks for reporting this issue. I created PR #16 which I believe fixes the problem. But I do not have access to a live Redfish service to test. Could you test the fix in PR #16 to confirm if it solves your issue?

It works here!! thanks  :)

**Comment by billdodd** [comment]
@abrother94 That's great! Thanks for checking it out.
