### ISSUE TITLE
The result of tool report different from manual test

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-Protocol-Validator#19]
Tool Version: 1.0.4
python3 rf_protocol_validator.py -r https://{IP} -u USERNAME -p PASSWORD --avoid-http-redirect --no-cert-check

SERV_EVENT_POST_RESP: "If the [Event Service] subscription request succeeds, the service shall return an HTTP 201 Created status code, and the Location header that contains a URI of the newly created subscription resource.

Message: 
Response from event subscription POST request to /redfish/v1/EventService/Subscriptions returned status code 400; expected 201; extended error: IP provided is invalid
Manual test result:
Check returned status code 201, and the Location header that contains a URI of the newly created subscription resource. 

Are there any verification procedures that prevent to verify completely? Did I lack step to verify this test case?

**Comment by mraineri** [comment]
Would you be able to provide what you did for your manual test? What was the request body when creating a new event subscription?

**Comment by FelixD999** [comment]
The request body of my creating subscription is as follows.
POST https://192.168.0.122/redfish/v1/EventService/Subscriptions
{
    "Context": "Event_Sub",
    "Destination": "https://192.168.0.110:4443",
    "Protocol": "Redfishhh",
    "EventFormatType": "Event",
    "RegistryPrefixes": [],
    "ResourceTypes": []
}

**Comment by mraineri** [comment]
What happens when you provide this as a payload in your manual test?

```
{
    "Context": "RPV test subscription",
    "Protocol": "Redfish",
    "Destination": "https://contoso.com/Destination1"
}
```

**Comment by mraineri** [comment]
Depending on the results of the request, we can make a change to the tool to use something like `https://192.168.1.1/Destination1` instead of `https://contoso.com/Destination1`.

**Comment by FelixD999** [comment]
When I provide that as a payload in manual test, it will return 400.
![POST400](https://user-images.githubusercontent.com/85208691/121323344-540b8e00-c942-11eb-93b1-926bc9a57803.JPG)

**Comment by mraineri** [comment]
@FelixD999 could you please try the branch in pull request #21 to see if that resolves the issue for you? Unfortunately I don't have a service with the same restriction yours does to test it myself.
