### ISSUE TITLE
Use of TRACE to validate 501/405 behavior issue with Apache implementations

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Protocol-Validator#20]
The test RESP_HEADERS_ALLOW_METHOD_NOT_ALLOWED uses the HTTP `TRACE` method to perform the check.  We are running into a security conflict here with an implementation based on Apache.  The Apache configuration option "TraceEnable Off" results in `TRACE` operations being denied before the request even reaches the Redfish Service.  But Apache is not filling out the `Allow` header, nor providing a means to do so, and so this results in a failure from the validator:
```
RESP_HEADERS_ALLOW_METHOD_NOT_ALLOWED: "[The Allow header] shall be returned with the HTTP 405 (Method Not Allowed) status code to indicate the valid methods for the request URI."
...
Result, Method, Status code, URI, Message,
FAIL, TRACE, 405, /redfish/v1/, The Allow header was missing from response to TRACE request to /redfish/v1/
```
While it is possible to work around this, doing so would be code solely to work around the validation test itself, rather than any actual issue with the Redfish service itself.

Suggest that the test be changed to use another valid HTTP operation that can be reliably "not supported" to perform this validation.  Our suggestion would be to perform a `DELETE` on the ServiceRoot (\redfish\v1) instead, since this should never be a supported operation.

**Comment by mraineri** [comment]
What do you return for other methods that are not allowed? At least with the way the spec is published today, there are two paths here:
* Return 405 with the Allow header
* Return 501

The Allow header is currently listed as mandatory in 405 responses.

**Comment by jautor** [comment]
Other methods are handled properly (and by the Redfish Service code) and return 405 with the `Allow` header.  It's specifically that Apache handles `TRACE` and doesn't give a way to affect that response.  The fact that Apache isn't matching the RFC behavior for 405 is something that should be raised with Apache, too.

**Comment by mraineri** [comment]
6/4: While the HTTP RFCs and the Redfish spec do call out requiring the Allow header with a 405 response, the spirit of the test is to be able to verify documented HTTP methods in the Redfish spec can be discovered as supported or not. TRACE is not part of the Redfish spec, so allowing this to pass through should be okay.

**Comment by jautor** [comment]
Note that we've entered an issue with Apache on the lack of the Allow header:
https://bz.apache.org/bugzilla/show_bug.cgi?id=65357

**Comment by mraineri** [comment]
@jautor can you try out the branch in pull request #22 to see if that resolves the issue?
