### ISSUE TITLE
About REQ_PATCH_ARRAY_TRUNCATE

### ISSUE THREAD

**Issue by JojoWu19** [DMTF/Redfish-Protocol-Validator#30]
This test case check if the array of response is the same with `expected_array` but it will report below cases failed.
1. fixed length array: there are `null` members are appended in the end of array.
2. the member has default value: some implemetations have default value for members, for example: "" or "0.0.0.0". If the member is deleted, it is given the default value.

I don't sure if the case 2 conforms to spec but validator should let case 1 pass, right?

**Comment by JojoWu19** [comment]
Get it, thank you.

**Comment by mraineri** [comment]
@JojoWu19 could you please try the Array-Test-Fixes branch? I don't have a system that performs the null padding at the end of the array to verify this myself.

**Comment by JojoWu19** [comment]
@mraineri It is passed in my side, and here is the debug log:
[debug.txt](https://github.com/DMTF/Redfish-Protocol-Validator/files/7114836/debug.txt)
