### ISSUE TITLE
SERV_SSE_EVENT_DEST_DELETED_ON_CLOSE should wait much longer than 3 seconds

### ISSUE THREAD

**Issue by blakehilliard** [DMTF/Redfish-Protocol-Validator#47]
I'm seeing this tool assert that SERV_SSE_EVENT_DEST_DELETED_ON_CLOSE fails, but that's only because it gives up after 3 seconds of closing the client side of the SSE connection.

At least in the framework I use for redfish SSE (WSGI), a close of the SSE client is only recognized on the next attempt to write to that connection, which will be on the next SSE heartbeat if no event occurs. And 3 seconds seems quite short for SSE heartbeat events to occur? Mine can take up to 20 seconds.

**Comment by mraineri** [comment]
By "SSE heartbeat", do you mean the socket keep-alive mechanism? I wouldn't expect explicit heartbeat messages sent over SSE since that should all be handled by the socket's keep-alive method itself.

**Comment by mraineri** [comment]
Gotcha, thanks for clarifying
