### ISSUE TITLE
Regarding the specification of AL

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-Protocol-Validator#54]
@FelixD999 I'm looking at the AL header test a bit more and I noticed that it looks like the contents of your header appear to be wrapped in double quotes; this is not expected. The test is examining the "path" portion of the URL and ignoring the rest.
_Originally posted by @mraineri in https://github.com/DMTF/Redfish-Protocol-Validator/issues/51#issuecomment-1398506972_

Hi,
After verified, the content of the AL header indeed be wrapped in double quotes.
![AL_header](https://user-images.githubusercontent.com/85208691/219868593-c76b0691-87db-473e-83a5-a86980b28c39.JPG)

I want to ask if there is an opportunity to optimize the tool so that the test process can skip the quotes.
Refered the [UPnP Device Architecture 2.0](https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf), but there seems to be no specification about the type of AL mentioned.

Thanks,
Felix

**Comment by mraineri** [comment]
All examples I've been finding for AL do not use double quotes. It doesn't seem to be common in other HTTP headers either to wrap string values like that in double quotes (like the Location header). It seems to be generally bad practice unless the encoding of the value requires double quotes for a particular header (like with ETags).

**Comment by FelixD999** [comment]
Got it, thank you very much for your reply.

**Comment by mraineri** [comment]
Closing; no plans on changing the tool since we're not expecting double quotes in the header. Please re-open if more discussion about this is needed.
