### ISSUE TITLE
Returned 202 status code after disabling SSDP

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-Protocol-Validator#55]
Hi,

Due to our design is return 202 after disabling SSDP, not sure if the root cause of the test case fail is about latency issues such that the Validator would still catch the response after disabling SSDP.
![report](https://user-images.githubusercontent.com/85208691/220895331-b589515a-c39f-46cd-b434-d9d25beb8e0a.JPG)

Thasnks,
Felix

**Comment by mraineri** [comment]
I think every implementation I've seen so far does not return a task when PATCHing that property (and other single properties like that in other resources). I've typically only seen tasks produced when invoking complex operations like a firmware update.

However, the spec does allow for a task to be returned on any operation; we'll need to update the tool to allow for that.

**Comment by FelixD999** [comment]
Thanks for your help, we look forward to updating from you.

**Comment by FelixD999** [comment]
Hi,
Due to our designed, we have other same issue about 202 return task, the following example is because the first task is still being processed, so the status returned by the subsequent PATCH will be 400:
![NTP_400](https://github.com/DMTF/Redfish-Protocol-Validator/assets/85208691/b08256b4-2d3a-4e8d-ad1e-1675fbfd8b38)

DEBUG:
![NTP](https://github.com/DMTF/Redfish-Protocol-Validator/assets/85208691/40ffcda5-3821-41a3-adce-780ec1a2a2a5)

Would it be possible for this part also adds the processing for task to be returned on operation?

Thanks,
Felix

**Comment by mraineri** [comment]
Can certainly look into adding task handling for other PATCH cases.
