### ISSUE TITLE
etag is mandatory or not

### ISSUE THREAD

**Issue by plmanik** [DMTF/Redfish-Protocol-Validator#62]
Hi,
As per redfish specification etag is recommended and not mandatory to implement

**To reduce unnecessary RESTful accesses to resources, the Redfish service should support the

association of a separate entity tag (ETag) with each resource.**

Is my understanding correct? 
But Redfish protocol Validator is throwing error as **User Accounts shall support etags and atomic operations**

Thanks,
Mani

**Comment by mraineri** [comment]
For ManagerAccount resources, it's mandatory. There's an additional statement in the same clause that elevates the ETag requirement for ManagerAccount resources:

> Implementations shall support the return of ETag headers for GET requests of ManagerAccount resources.

**Comment by plmanik** [comment]
Hi,
Got it. Sorry for missing mandatory for ManagerAccount resources. I hope ManagerAccount  resources means ManagerAccount   collection, ManagerAccount   instance needs to implement etag. Please close this issue

Thanks,
Mani
