### ISSUE TITLE
/archive/reds/tags/{file}.zip points to a different version as the name of the {file}.

### ISSUE THREAD

**Issue by leoprovido** [DMTF/Redfish-Protocol-Validator#70]
Hi @mraineri ,

In https://github.com/DMTF/Redfish-Protocol-Validator/releases, I noticed that when I download https://github.com/DMTF/Redfish-Protocol-Validator/archive/refs/tags/1.1.9.zip, the downloaded zip file appears to be 1.1.8.

![image](https://github.com/DMTF/Redfish-Protocol-Validator/assets/47441723/13cb41ee-c6b7-4271-b352-a12cb8fdee17)

I don't see this behavior in other repositories like https://github.com/DMTF/Redfish-Interop-Validator/releases.
For example, https://github.com/DMTF/Redfish-Interop-Validator/archive/refs/tags/2.1.4.zip

![image](https://github.com/DMTF/Redfish-Protocol-Validator/assets/47441723/a1967115-8884-4e3b-aeb9-c3eb0cc4065d)

**Comment by mraineri** [comment]
I'm seeing the same issue on the service validator... The interop validator is using a slightly different workflow for making a release, which I'm actually changing to be more consistent with what appears to be the "right" method (using the `actions/create-release`). It seems like the versioning/changelog updates pushed in the previous step don't get picked up by the action... Will need to look at this more...

**Comment by mraineri** [comment]
Well, I just noticed the repo for that action is marked as read-only and unmaintained... I think I'll use the same workflow step used in the interop validator to make the release.
