### ISSUE TITLE
Tool no longer works with python 3.6

### ISSUE THREAD

**Issue by blakehilliard** [DMTF/Redfish-Protocol-Validator#72]
The increase to depending on requests 2.30+ in https://github.com/DMTF/Redfish-Protocol-Validator/commit/aaed04248a8d8dfb71c3dbcb0b1dcfb465c9070e makes this tool no longer work with python 3.6, due to the newest versions of requests no longer supporting that version of python.

But pypi for this tool claims support with python 3.5+ https://pypi.org/project/redfish-protocol-validator/

I'm hoping the requests dependency could be dropped to older versions again? If 2.30+ is really needed, then the supported python versions need to be updated in pypi.

**Comment by mraineri** [comment]
Yes, it is needed unfortunately. urllib3 has necessary fixes with newer versions of Python, which in turn requires newer requests... And unfortunately it looks like Python3.6 has been dropped by the general community.

**Comment by mraineri** [comment]
I guess we could just turn off the version enforcement for requests; at that point your left to your Python environment to ensure you have everything in place. But given how everything has been moving forward, I suspect you'll hit issues with Python3.6 at some point.

**Comment by mraineri** [comment]
Closing; removed all version restrictions in the requirements file. At this point, it's at the user's risk if they want to try to run with Python3.6.
