### ISSUE TITLE
Debug log about AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-Protocol-Validator#75]
Hi,
When I run with version 1.2.3 it gets blocked at AttributeError: 'list' object has no attribute 'get'. 
![protocol_1 2 3_list](https://github.com/DMTF/Redfish-Protocol-Validator/assets/85208691/ab5136b1-a901-4e81-868d-cb5d037d5941)

I checked the patch_array_save in service_requests.py according to the debug log, but I am not sure whether the root cause is related to this. Could you please help explain?

Thanks,
Felix

**Comment by mraineri** [comment]
It looks like it might be related to the response payload for ManagerNetworkProtocol; I'm suspecting "NTP" is an array in the response, which should be an object. Can you provide the response body for your ManagerNetworkProtocol resource?

**Comment by FelixD999** [comment]
Thanks for your explanation and tips. Previously "NTP" did become an array, now we have corrected it back to object and running the validator will not be blocked by this issue.
